# http://wiki.ros.org/navfn
GlobalPlanner:
  lethal_cost:                  100   #default: 253
  neutral_cost:                 50    #default: 50
  cost_factor:                  3.0   #default: 3.0
  orientation_mode:             1     #default: 1-Forward
  publish_potential:            false #default: false

#http://wiki.ros.org/base_local_planner
TrajectoryPlannerROS:
  # Robot Configuration Parameters
  acc_lim_x:                    2.5     #default 2.5
  acc_lim_y:                    2.5     #default 2.5
  acc_lim_theta:                3.2     #default 3.2
  max_vel_x:                    1.0     #default 0.5
  min_vel_x:                    0.1     #default 0.1
  max_vel_theta:                1.0     #default 1.0
  min_vel_theta:                -1.0    #default -1.0
  min_in_place_vel_theta:       0.4     #default 0.4
  escape_vel:                   -0.1    #default -0.1
  holonomic_robot:              true   #default true

  # The following parameters are only used if holonomic_robot is set to true:
  y_vels: [-0.3, -0.1, 0.1, 0.3] #default [-0.3, -0.1, 0.1, 0.3]

  # Goal Tolerance Parameters		
  yaw_goal_tolerance:           0.1     #default 0.05
  xy_goal_tolerance:            0.2     #default 0.1
  latch_xy_goal_tolerance:      false   #default false
  
  # Forward Simulation Parameters
  sim_time:                     1.7     #default 1.0
  sim_granularity:              0.025   #default 0.025
  angular_sim_granularity:      0.025   #default 0.025
  vx_samples:                   6       #default 3
  vtheta_samples:               10      #default 10
  controller_frequency:         20.0    #default 20.0
  
  # Trajectory Scoring Parameters
  # Whether the gdist_scale and pdist_scale parameters should assume that goal_distance and
  # path_distance are expressed in units of meters or cells.
  meter_scoring:                true    #default false
  # The weighting for how much the controller should stay close to the path it was given
  pdist_scale:                  0.6      #default 0.6
  # The weighting for how much the controller should attempt to reach its local goal, also controls speed
  gdist_scale:                  0.8      #default 0.8
  # The weighting for how much the controller should attempt to avoid obstacles.
  occdist_scale:                0.01    #default 0.01
  # How far to look ahead in meters when scoring different in-place-rotation trajectories
  heading_lookahead:            0.5     #default 0.325
  # Whether to score based on the robot's heading to the path or its distance from the path.
  heading_scoring:              false   #default false
  # How far to look ahead in time in seconds along the simulated trajectory when using heading scoring
  heading_scoring_timestep:     0.8     #default 0.8
  # Whether to use the Dynamic Window Approach (DWA)_ or whether to use Trajectory Rollout;
  # should be set to FALSE if using the Trajectory planner use DWA planner if you want DWA
  dwa:                          false   #default true
  # Whether to publish cost grid pointcloud; used for debugging and integration
  publish_cost_grid_pc:         false   #default false
  # Global frame of the planner
  global_frame_id:              /odom   #default odom

  # Oscillation Prevention Parameters
  # How far the robot must travel in meters before oscillation flags are reset
  oscillation_reset_dist:       0.025    #default 0.05

  # Global Plan Parameters
  prune_plan:                   true    #default true
