# 2D Costmap parameters
# http://www.ros.org/wiki/costmap_2d

### Coordinate frame and tf parameters ###
robot_base_frame:           base_link
transform_tolerance:        1.5

# ---Vector footprint (Meters):---
footprint: [[0.365163875,0.27580937],[0.365163875,-0.27580937],[-0.365163875,-0.27580937],[-0.365163875,0.27580937]]

# The following parameter is overwritten if the "footprint" parameter is set
#robot_radius:               0.325

### Costmap layer definitions ###
publish_frequency:           1.0
plugins:                     []

static:
  unknown_cost_value:        -1
  lethal_cost_threshold:     100
  map_topic:                 map
  subscribe_to_updates:      true

obstacles_costmap2d:
  observation_sources: movo_scan
  movo_scan: {topic:                   /movo/base_scan_filtered,
                data_type:               LaserScan,
                marking:                 true,
                clearing:                true,
                obstacle_range:          3.5,
                raytrace_range:          4.0}

inflation:
  inflation_radius:           0.55 #default 0.5
  cost_scaling_factor:        10.0 #default 10.0

