#!/bin/bash

echo -e "This script will give access to the Internet to MOVO1 and upgrade its OS to Ubuntu 16.04.\nMAKE SURE YOU HAVE A BACKUP IMAGE OF THIS COMPUTER!"

read -r -p "Are you absolutely sure you want to continue? [y/n]" response
if [[ "$response" =~ ^([yY][eE][sS]|[yY])+$ ]]
then
    echo "Starting internet connection setup..."
    sleep 1
else
    echo "Aborting."
    exit 1
fi

sudo iptables -F
sudo iptables -t nat -F
sudo iptables -t mangle -F
sudo iptables -X
sudo iptables -t nat -X
sudo iptables -t mangle -X

iptables-save | sudo tee /etc/network/iptables.rules

echo 1 | sudo tee /proc/sys/net/ipv4/ip_forward > /dev/null
sudo iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE

iptables-save | sudo tee /etc/network/iptables.rules

ssh movo1 'sudo ip route del default; sudo ip route add default via 10.66.171.1; echo "nameserver 8.8.4.4" | sudo tee /etc/resolv.conf > /dev/null'

# Uncomment to update packages and upgrade OS
#echo "MOVO1 is online.\nUpdating packages..."
#ssh movo1 "sudo apt-get update -y"
#echo "MOVO1 will be upgraded to Ubuntu 16.04.\nYou will be prompted a couple times during the installation process.\n"
#ssh movo1 "sudo do-release-update"

exit 1