use_odom:                             true
use_vel:                              false
use_imu:                              true
max_iterations:                       10
publish_tf:                           false
publish_pose:                         false
publish_pose_stamped:                 false
publish_pose_with_covariance:         false
publish_pose_with_covariance_stamped: true
fixed_frame:                          odom
use_cloud_input:                      false
cloud_range_min:                      0.05
cloud_range_max:                      10.0
kf_dist_linear:                       0.10
kf_dist_angular:                      0.175
max_correspondence_dist:              0.3
max_angular_correction_deg:           10.0
max_linear_correction:                0.2
epsilon_xy:                           0.00001
epsilon_theta:                        0.00001
outliers_maxPerc:                     0.9
sigma:                                0.04
use_corr_tricks:                      1
restart:                              0
restart_threshold_mean_error:         0.01
restart_dt:                           1.0
restart_dtheta:                       0.1
clustering_threshold:                 0.25
orientation_neighbourhood:            10
use_point_to_line_distance:           1
do_alpha_test:                        0
do_alpha_test_thresholdDeg:           20.0
outliers_adaptive_order:              0.7
outliers_adaptive_mul:                2.0
do_visibility_test:                   0
outliers_remove_doubles:              1
do_compute_covariance:                0
debug_verify_trick:                   0
use_ml_weights:                       0
use_sigma_weights:                    0

