###########################################################
# This action is called for integrated object detection and
#  grasp planning, such as in base_grasping_perception

# Set to false to disable grasp planning, returning only the objects found
bool plan_grasps
int32 gripper
---
# Graspable objects found
GraspableObject[] objects

# Additional, non-graspable objects which may be support surfaces
Object[] support_surfaces
---
# Publish objects as they are detected and grasp planned
GraspableObject object
