# yaml file for package simple_grasping with rosnode "basic_grasping_perception"
############################################################################
left_gripper:
  left_joint: left_gripper_finger1_joint
  right_joint: left_gripper_finger2_joint
  max_opening: 0.165
  max_effort: 1.5
  invert_gripper: true
  tool_to_planning_frame: 0.0    # should be 0.165 after fix the simple_grasping 
  finger_depth: 0.020
  gripper_tolerance: 0.01
  grasp_duration: 4.0
  approach:
    min: 0.145
    desired: 0.15
  retreat:
    min: 0.145
    desired: 0.15
    
right_gripper:
  left_joint: right_gripper_finger1_joint
  right_joint: right_gripper_finger2_joint
  max_opening: 0.165
  max_effort: 1.5
  invert_gripper: true
  tool_to_planning_frame: 0.0    # should be 0.165 after fix the simple_grasping 
  finger_depth: 0.020
  gripper_tolerance: 0.01
  grasp_duration: 4.0
  approach:
    min: 0.145
    desired: 0.15
  retreat:
    min: 0.145
    desired: 0.15
