#
# http://www.ros.org/wiki/amcl
# The first commented value is the default per the wiki
# The second commented value is the default per nav/amcl/examples
# The third commented value is the defaults in amcl_node.cpp
#
# The map file is specified in launch/amcl.launch

odom_frame_id:    odom
base_frame_id:    base_link
global_frame_id:  map
  
# Overall filter parameters
min_particles:        100       #default 100
max_particles:        2000      #default 5000
kld_err:              0.05      #default 0.01
kld_z:                0.95      #default 0.99
update_min_d:         0.1       #default 0.2
update_min_a:         0.25      #default pi/6 (0.5235)
resample_interval:    2         #default 1
transform_tolerance:  1.0       #default 0.1
recovery_alpha_slow:  0.001     #default 0.0
recovery_alpha_fast:  0.1       #default 0.0
initial_pose_x:       0.0       #default 0.0
initial_pose_y:       0.0       #default 0.0
initial_pose_a:       0.0       #default 0.0
initial_cov_xx:       0.1      #default 0.25
initial_cov_yy:       0.1       #default 0.25
initial_cov_aa:       0.12    #default (pi/12)*(pi/12) (0.06853)
gui_publish_rate:     -1.0      #default -1.0
save_pose_rate:       0.5       #default 0.5
use_map_topic:        false     #default false
first_map_only:       false     #default false

# Laser Model Parameters 
laser_min_range:            0.1    #default -1.0
laser_max_range:            9.0    #default -1.0
laser_max_beams:            60     #default 30
laser_z_hit:                0.90   #default 0.95
laser_z_rand:               0.1   #default 0.05
laser_sigma_hit:            0.1   #default 0.2  
laser_lambda_short:         0.1   #default 0.1
laser_likelihood_max_dist:  3.0    #default 2.0
laser_model_type:           likelihood_field #default likelihood_field

# Odometery model parameters
odom_model_type:  omni
odom_alpha1:      0.1     #default 0.2 rotational    drift caused by rotation
odom_alpha2:      0.1     #default 0.2 rotational    drift caused by translation
odom_alpha3:      0.1     #default 0.2 translational drift caused by translation
odom_alpha4:      0.1     #default 0.2 translational drift caused by rotation
odom_alpha5:      0.1     #default 0.2 Holonomic drive systems only
