#
# http://wiki.ros.org/move_base
#
planner_frequency:          0.0     # default: 0.0 Global plan updates on new goal or path blocked only
controller_frequency:       10.0    # default: 20.0
planner_patience:           5.0     # default: 5.0
controller_patience:        10.0    # default: 15.0
conservative_reset_dist:    3.0     # default: 3.0
recovery_behavior_enabled:  true    # default: true
clearing_rotation_allowed:  true    # default: true
shutdown_costmaps:          false   # default: false
oscillation_timeout:        5.0     # default: 0.0
oscillation_distance:       0.05     # default: 0.5

recovery_behaviors: [
  {name: conservative_reset, type: clear_costmap_recovery/ClearCostmapRecovery},
  {name: rotate_recovery1, type: rotate_recovery/RotateRecovery},
  {name: aggressive_reset, type: clear_costmap_recovery/ClearCostmapRecovery},
  {name: rotate_recovery2, type: rotate_recovery/RotateRecovery}
]

conservative_clear:
  reset_distance: 3.0
agressive_clear:
  reset_distance: 1.875

