TebLocalPlannerROS:
   
    # Trajectory

    teb_autosize: True
    dt_ref: 0.3
    dt_hysteresis: 0.03
    global_plan_overwrite_orientation: True
    allow_init_with_backwards_motion: True
    max_global_plan_lookahead_dist: 1.5
    feasibility_check_no_poses: 5
    min_samples: 5

    # Robot
         
    max_vel_x: 0.4
    max_vel_x_backwards: 0.2
    max_vel_y: 0.1
    max_vel_theta: 0.3
    acc_lim_x: 0.5
    acc_lim_y: 0.2
    acc_lim_theta: 0.5
    min_turning_radius: 0.0 # omni-drive robot (can turn on place!)

    footprint_model:
        type: "polygon"
        vertices: [[0.365163875,0.27580937],[0.365163875,-0.27580937],[-0.365163875,-0.27580937],[-0.365163875,0.27580937]]

    # GoalTolerance

    xy_goal_tolerance: 0.2
    yaw_goal_tolerance: 0.2
    free_goal_vel: False

    # Obstacles

    min_obstacle_dist: 0.1 # This value must also include our robot radius, since footprint_model is set to "point".
    include_costmap_obstacles: True
    costmap_obstacles_behind_robot_dist: 1.0
    obstacle_poses_affected: 30
    costmap_converter_plugin: ""
    costmap_converter_spin_thread: True
    costmap_converter_rate: 5

    # Optimization

    no_inner_iterations: 5
    no_outer_iterations: 4
    optimization_activate: True
    optimization_verbose: False
    penalty_epsilon: 0.1
    weight_max_vel_x: 4.0
    weight_max_vel_y: 4.0
    weight_max_vel_theta: 4.0
    weight_acc_lim_x: 1.0
    weight_acc_lim_y: 1.0
    weight_acc_lim_theta: 1.0
    weight_kinematics_nh: 0.01 # WE HAVE A HOLONOMIC ROBOT, JUST ADD A SMALL PENALTY
    weight_kinematics_forward_drive: 0.01
    weight_kinematics_turning_radius: 0.01
    weight_optimaltime: 1.0
    weight_obstacle: 25.0

    # Homotopy Class Planner

    enable_homotopy_class_planning: True
    enable_multithreading: True
    simple_exploration: False
    max_number_classes: 5
    selection_cost_hysteresis: 1.5
    selection_obst_cost_scale: 1.5
    selection_alternative_time_cost: False

    roadmap_graph_no_samples: 15
    roadmap_graph_area_width: 3.0
    h_signature_prescaler: 0.75
    h_signature_threshold: 0.1
    obstacle_keypoint_offset: 0.1
    obstacle_heading_threshold: 0.75
    visualize_hc_graph: False
    odom_topic: /movo/odometry/local_filtered
