global_costmap:
    global_frame:         odom
    rolling_window:       true
    track_unknown_space:  true

    plugins:
        - {name: obstacles_costmap2d,       type: "costmap_2d::ObstacleLayer"}
        - {name: inflation,                 type: "costmap_2d::InflationLayer"}
  




