# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  left_arm_half_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 1.0
  left_elbow_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 1.0
  left_gripper_finger1_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 1.0
  left_gripper_finger2_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 1.0
  left_gripper_finger3_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 1.0
  left_shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 1.0
  left_shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 1.0
  left_wrist_3_joint:
    has_velocity_limits: true
    max_velocity: 0.7
    has_acceleration_limits: true
    max_acceleration: 1.0
  left_wrist_spherical_1_joint:
    has_velocity_limits: true
    max_velocity: 0.7
    has_acceleration_limits: true
    max_acceleration: 1.0
  left_wrist_spherical_2_joint:
    has_velocity_limits: true
    max_velocity: 0.7
    has_acceleration_limits: true
    max_acceleration: 1.0
  linear_joint:
    has_velocity_limits: true
    max_velocity: 0.2
    has_acceleration_limits: true
    max_acceleration: 1.0
  pan_joint:
    has_velocity_limits: true
    max_velocity: 0.7
    has_acceleration_limits: true
    max_acceleration: 1.0
  right_arm_half_joint:
    has_velocity_limits: true
    max_velocity: 0.7
    has_acceleration_limits: true
    max_acceleration: 1.0
  right_elbow_joint:
    has_velocity_limits: true
    max_velocity: 0.7
    has_acceleration_limits: true
    max_acceleration: 1.0
  right_gripper_finger1_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 1.0
  right_gripper_finger2_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 1.0
  right_gripper_finger3_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 1.0
  right_shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 1.0
  right_shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 1.0
  right_wrist_3_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 1.0
  right_wrist_spherical_1_joint:
    has_velocity_limits: true
    max_velocity: 0.7
    has_acceleration_limits: true
    max_acceleration: 1.0
  right_wrist_spherical_2_joint:
    has_velocity_limits: true
    max_velocity: 0.7
    has_acceleration_limits: true
    max_acceleration: 1.0
  tilt_joint:
    has_velocity_limits: true
    max_velocity: 0.7
    has_acceleration_limits: true
    max_acceleration: 1.0