#!/usr/bin/env python
"""--------------------------------------------------------------------
Copyright (c) 2017, Kinova Robotics inc.

All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice,
      this list of conditions and the following disclaimer in the documentation
      and/or other materials provided with the distribution.
    * Neither the name of the copyright holder nor the names of its contributors
      may be used to endorse or promote products derived from this software
      without specific prior written permission.
      
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR 
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR 
CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, 
EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR 
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF 
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING 
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS 
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
 \file   init_sim.py

 \brief  This node serves to setup simulation 

 \Platform: Linux/ROS Indigo
--------------------------------------------------------------------"""
import rospy,time,rospkg,rosnode
import random
from gazebo_msgs.srv import DeleteModel,DeleteModelRequest,SpawnModel,SpawnModelRequest
from std_srvs.srv import Empty,EmptyRequest
from movo_action_clients.gripper_action_client import GripperActionClient

if __name__ == "__main__":
    rospy.init_node('reset_objects')
    rospack = rospkg.RosPack()
    rosnode.kill_nodes(['/basic_grasping_perception','demo'])
    time.sleep(1)
    lgripper = GripperActionClient('left')
    rgripper = GripperActionClient('right')
    
    lgripper.command(0.0)
    rgripper.command(0.0)
    lgripper.wait()
    rgripper.wait()
    time.sleep(3)
    rgripper.shutdown()
    lgripper.shutdown()
    del lgripper
    del rgripper
    
    clr = rospy.ServiceProxy('clear_octomap',Empty)
    smd = rospy.ServiceProxy('gazebo/delete_model',DeleteModel)
    smp = rospy.ServiceProxy('gazebo/spawn_sdf_model',SpawnModel)

    tmp = DeleteModelRequest()
    tmp.model_name = 'cafe_beer'
    smd.call(tmp)
    tmp = DeleteModelRequest()
    tmp.model_name = 'pringles'
    smd.call(tmp)
    time.sleep(1)
    
    f = open(rospack.get_path("movo_gazebo")+'/models/cafe_beer/model.sdf','r')
    sdff = f.read()
    f.close()
    
    tmp = SpawnModelRequest()
    tmp.model_name='cafe_beer'
    tmp.model_xml = sdff
    tmp.robot_namespace=''
    tmp.reference_frame="world"
    tmp.initial_pose.position.x = random.uniform(3.7,3.9) 
    tmp.initial_pose.position.y = random.uniform(3.1,3.4) 
    tmp.initial_pose.position.z = 0.86
    smp.call(tmp)

    f = open(rospack.get_path("movo_gazebo")+'/models/pringles/model.sdf','r')
    sdff = f.read()
    f.close()
    
    tmp = SpawnModelRequest()
    tmp.model_name='pringles'
    tmp.model_xml = sdff
    tmp.robot_namespace=''
    tmp.reference_frame="world"
    tmp.initial_pose.position.x = random.uniform(3.7,3.9) 
    tmp.initial_pose.position.y = random.uniform(2.7,2.9) 
    tmp.initial_pose.position.z = 0.86
    smp.call(tmp)
    
    clr.call(EmptyRequest())
    
    smp.close()
    smd.close()
    clr.close()

