controller_list:
  - name: fake_left_arm_controller
    joints:
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint
  - name: fake_left_gripper_controller
    joints:
      - left_gripper_finger1_joint
  - name: fake_torso_controller
    joints:
      - linear_joint
  - name: fake_head_controller
    joints:
      - pan_joint
      - tilt_joint
  - name: fake_upper_body_controller
    joints:
      - linear_joint
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint
      - pan_joint
      - tilt_joint
