controller_list:
  - name: fake_right_arm_controller
    joints:
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
      - right_wrist_3_joint
  - name: fake_right_gripper_controller
    joints:
      - right_gripper_finger1_joint
  - name: fake_torso_controller
    joints:
      - linear_joint
  - name: fake_head_controller
    joints:
      - pan_joint
      - tilt_joint
  - name: fake_upper_body_controller
    joints:
      - linear_joint
      - pan_joint
      - tilt_joint
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
      - right_wrist_3_joint
