sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /kinect/sd/points
    max_range: 2.0
    point_subsample: 1
    padding_offset: 0.05
    padding_scale: 1.0
    filtered_cloud_topic: filtered_cloud
